version: '3'
services:
  api:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    volumes:
      - ${BROWSE_DIR}:/videos
      - ./server/:/app
    environment:
      - BROWSE_DIR=/videos
    ports:
      - '3000:3000'
